[2025-03-02 06:09:33,391: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 06:16:25,003: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 06:26:11,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 06:28:57,554: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 06:32:02,468: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 06:39:09,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 07:54:36,650: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:13:45,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:13:57,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:21:39,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:21:50,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:22:56,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:32:13,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 08:32:32,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-02 11:40:44,675: INFO: main: welcome to our custom logging data science]
[2025-03-02 11:40:44,679: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 11:40:44,698: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 11:40:44,789: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 11:40:44,818: ERROR: main: YAML file is empty]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 19, in read_yaml
    return ConfigBox(content)  # Return an instance of ConfigBox
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 22, in read_yaml
    raise ValueError("YAML file is empty")
ValueError: YAML file is empty
[2025-03-02 11:43:50,788: INFO: main: welcome to our custom logging data science]
[2025-03-02 11:43:50,792: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 11:43:50,814: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 11:43:50,840: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 11:43:50,846: ERROR: main: YAML file is empty]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 20, in read_yaml
    return ConfigBox(content)  # Return an instance of ConfigBox
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 23, in read_yaml
    raise ValueError("YAML file is empty")
ValueError: YAML file is empty
[2025-03-02 11:54:26,715: INFO: main: welcome to our custom logging data science]
[2025-03-02 11:54:26,722: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 11:54:26,856: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 11:54:27,021: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 11:54:27,030: ERROR: main: YAML file is empty]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 20, in read_yaml
    return ConfigBox(content)  # Return an instance of ConfigBox
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 23, in read_yaml
    raise ValueError("YAML file is empty")
ValueError: YAML file is empty
[2025-03-02 11:55:49,780: INFO: main: welcome to our custom logging data science]
[2025-03-02 11:55:49,784: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 11:55:49,800: ERROR: main: name 'logging' is not defined]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 21, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 23, in read_yaml
    logging.error(f"Error reading YAML file {path}: {e}")
NameError: name 'logging' is not defined
[2025-03-02 11:58:27,546: INFO: main: welcome to our custom logging data science]
[2025-03-02 11:58:27,564: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 11:58:27,605: ERROR: common: Error reading YAML file params.yaml: Cannot extrapolate Box from string]
[2025-03-02 11:58:27,614: ERROR: main: Cannot extrapolate Box from string]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\venv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 22, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string
[2025-03-02 12:09:06,773: INFO: main: welcome to our custom logging data science]
[2025-03-02 12:09:06,776: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 12:09:07,049: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 12:09:07,058: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 12:09:07,060: ERROR: common: BoxValueError: Cannot extrapolate Box from string]
[2025-03-02 12:09:07,062: ERROR: main: YAML file is empty or invalid.]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 34, in read_yaml
    raise ValueError("YAML file is empty or invalid.")
ValueError: YAML file is empty or invalid.
[2025-03-02 12:23:50,271: INFO: main: welcome to our custom logging data science]
[2025-03-02 12:23:50,275: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 12:23:50,614: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 12:23:50,623: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 12:23:50,625: ERROR: common: BoxValueError: Cannot extrapolate Box from string]
[2025-03-02 12:23:50,627: ERROR: main: YAML file is empty or invalid.]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 12, in __init__
    self.params= read_yaml(params_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 34, in read_yaml
    raise ValueError("YAML file is empty or invalid.")
ValueError: YAML file is empty or invalid.
[2025-03-02 12:31:25,679: INFO: main: welcome to our custom logging data science]
[2025-03-02 12:31:25,684: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 12:31:25,713: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 12:31:25,732: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 12:31:26,042: INFO: common: YAML file: schema.yaml loaded successfully]
[2025-03-02 12:31:26,044: ERROR: common: BoxValueError: Cannot extrapolate Box from string]
[2025-03-02 12:31:26,046: ERROR: main: YAML file is empty or invalid.]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 13, in __init__
    self.schema= read_yaml(schema_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 34, in read_yaml
    raise ValueError("YAML file is empty or invalid.")
ValueError: YAML file is empty or invalid.
[2025-03-02 12:33:44,775: INFO: main: welcome to our custom logging data science]
[2025-03-02 12:33:44,798: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 12:33:45,109: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 12:33:45,118: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 12:33:45,124: INFO: common: YAML file: schema.yaml loaded successfully]
[2025-03-02 12:33:45,127: ERROR: common: BoxValueError: Cannot extrapolate Box from string]
[2025-03-02 12:33:45,152: ERROR: main: YAML file is empty or invalid.]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 13, in __init__
    self.schema= read_yaml(schema_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 34, in read_yaml
    raise ValueError("YAML file is empty or invalid.")
ValueError: YAML file is empty or invalid.
[2025-03-02 12:50:52,517: INFO: main: welcome to our custom logging data science]
[2025-03-02 12:50:52,611: INFO: main: >>>>>>>> stage  Data Ingestion stage started <<<<<]
[2025-03-02 12:50:52,760: INFO: common: YAML file: config\config.yaml loaded successfully]
[2025-03-02 12:50:52,831: INFO: common: YAML file: params.yaml loaded successfully]
[2025-03-02 12:50:52,836: INFO: common: YAML file: schema.yaml loaded successfully]
[2025-03-02 12:50:52,875: ERROR: common: BoxValueError: Cannot extrapolate Box from string]
[2025-03-02 12:50:52,916: ERROR: main: YAML file is empty or invalid.]
Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 30, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 283, in box.box.Box.__init__
box.exceptions.BoxValueError: Cannot extrapolate Box from string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\main.py", line 13, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\pipeline\data_ingestion_pipeline.py", line 12, in initiate_data_ingestion
    config=ConfigurationManager()
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\config\configuration.py", line 13, in __init__
    self.schema= read_yaml(schema_filepath)
  File "C:\Users\lenovo\Documents\mlopsetl_project\ETL_pipeline_mlproject\src\ETL_pipeline_mlproject\utils\common.py", line 34, in read_yaml
    raise ValueError("YAML file is empty or invalid.")
ValueError: YAML file is empty or invalid.
